import { StyleSheet } from 'react-native'

const styles = StyleSheet.create({
    main:{
        backgroundColor:'#6e6e6e',
        width:"100%",
        height:"100%"
    },
    topCon:{
        width:'90%',
        marginLeft:'5%',
        marginTop:40,
        borderTopLeftRadius:10,
        borderTopRightRadius:10,
        padding:10
    },
    marginTop20:{
        marginTop:20
    },
    TopImg:{
        width:30,
        height:30,
        borderRadius:15
    },
    blackJiao:{
        color:"#fce9e1",
        fontWeight:'bold'

    },
    sub_title:{
        color:"#c5c5c5",
        fontSize:9
    },
    memberCenter:{
        width:60,
        height:20,
        borderRadius:10,
    },
    memberCenterText:{
        lineHeight:20,
        fontSize:12,
        textAlign:'center',
    },
    flexBet:{ 
        display:'flex',
        flexDirection:'row',
        justifyContent:'space-between'
    },
    first_mon:{
        color:"#feeeef",
        fontSize:11
    },
    centerCon:{
        backgroundColor:'#fff',
        borderTopLeftRadius:10,
        borderTopRightRadius:10,
        padding:15
    },
    qiandao:{
        height:20,
        backgroundColor:'#fd3938',
        borderRadius:10,
        width:50,
        marginTop:5
    },
    qiandaoText:{
        color:'#fff',
        textAlign:'center',
        lineHeight:20,
        fontSize:10,
    },
    userName:{
        fontSize:12,
        marginLeft:8,
        marginTop:8
    },
    marginTop10:{
        marginTop:10
    },
    iconImg:{
        width:25,
        height:17,
        justifyContent:'space-around'
    },
    foruItem:{
        width:"100%",
        justifyContent:"space-around",
        flexDirection:'row',
        marginBottom:8
    },
    foruItemtext:{
        fontSize:10,
        textAlign:'center'
    },
    listCon:{
 
        borderTopColor:'#f0f0f0',
        borderTopWidth:1,
        borderStyle:'solid'
    },
    listItem:{
        flexDirection:'row',
        paddingBottom:10,
        paddingTop:10
    },
    itemIcon:{
        width:20,
        height:20,
        marginRight:10
    },
    itemText:{
        color:'#3a3a3a',
        fontSize:11,
        marginTop:2
    },
    fixedBottom:{
        position:"absolute",
        bottom:0,
        width:"100%",
        flexDirection:"row",
        backgroundColor:'#fff',
        justifyContent:"space-between",
        padding:15,
        borderTopColor:'#f0f0f0',
        borderTopWidth:1,
        borderStyle:'solid'
    },
    flexBottomItem:{
        flexDirection:'row'
    }
})


export default styles